dpi:
    client:
        keystore:
            alias: ''
            lockProvider: false
            password: ''
            path: ''
            type: jks
        uri: 'http://localhost:8081/dpi'
spring:
    main:
        web-application-type: NONE
