dpi:
    client:
        keystore:
            alias: ''
            lockProvider: false
            password: ''
            path: ''
            type: jks
        uri: 'http://localhost:8081/dpi'
        oidc:
            url: 'https://ver2.maskinporten.no/token'
            audience: 'https://ver2.maskinporten.no/'
            clientId: 'dpi_test'
            scopes:
                - dummy
            keystore:
                alias: ${dpi.client.keystore.alias}
                lockProvider: ${dpi.client.keystore.lockProvider}
                password: ${dpi.client.keystore.password}
                path: ${dpi.client.keystore.path}
                type: ${dpi.client.keystore.type}
spring:
    main:
        web-application-type: NONE
