dpi:
    client:
        type: file
        schema: offline
        certificate:
            mode: TEST
        keystore:
            alias: ''
            lockProvider: false
            password: ''
            path: ''
            type: jks
        uri: 'http://localhost:8081/dpi'
        oidc:
            enable: true
            url: 'https://ver1.maskinporten.no/token'
            audience: 'https://ver1.maskinporten.no/'
            send:
                clientIdPrefix: 'MOVE_IP_'
            receive:
                clientId: 'MOVE_IP_991825827'
            scopes:
                - digitalpostinnbygger:send
            keystore:
                alias: ${dpi.client.keystore.alias}
                lockProvider: ${dpi.client.keystore.lockProvider}
                password: ${dpi.client.keystore.password}
                path: ${dpi.client.keystore.path}
                type: ${dpi.client.keystore.type}
        temporary-file-threshold: 10000000
        initialBufferSize: 100000
spring:
    main:
        web-application-type: NONE
