dpi:
    client:
        type: file
        schema: online
        keystore:
            alias: ''
            lockProvider: false
            password: ''
            path: ''
            type: jks
        uri: 'http://localhost:8081/dpi'
        oidc:
            enable: true
            url: 'https://ver1.maskinporten.no/token'
            jwkUrl: 'https://ver1.maskinporten.no/jwk'
            audience: 'https://ver1.maskinporten.no/'
            clientId: 'dpi_test'
            scopes:
                - digitalpostinnbygger:send
            keystore:
                alias: ${dpi.client.keystore.alias}
                lockProvider: ${dpi.client.keystore.lockProvider}
                password: ${dpi.client.keystore.password}
                path: ${dpi.client.keystore.path}
                type: ${dpi.client.keystore.type}
        temporary-file-threshold: 10000000
        initialBufferSize: 100000
spring:
    main:
        web-application-type: NONE
